name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Postgres 15
        uses: docker://postgres:15
        with:
          args: -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=laravel -p 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: intl, zip, pcntl, gd, pdo_pgsql, pgsql, bcmath, sockets, opcache, exif, imagick, redis, swoole
          coverage: none
          ini-values: xdebug.mode=off
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --no-suggest --prefer-dist
          npm install
      - name: Copy .env
        run: |
          cp .env.ci .env
      - name: Generate key
        run: |
          php artisan key:generate
      - name: Run tests
        run: |
          php artisan test
          npm run test
